### ISSUE TITLE
Ajustar requisição frontend

### ISSUE THREAD

**Issue by jpcirqueira** [fga-eps-mds/2022-1-Alectrion-DOC#117]
**Descrever o bug**
Frontend está buscando direto do serviço user

**Como reproduzir o bug**
Passos para ocorrer o bug:
1. Entrar na tela de criação de usuário

**Comportamento Esperado**
deve requisitar a porta 4000 ao invés da 4001

**Desktop / computadores (informe as características do computador utilizado):**
 - Sistema Operacional: [e.g. Windows, Linux]
 - Navegador [e.g. chrome, safari]
 - Versão [e.g. 22]

**Comment by wildemberg-sales** [comment]
Sobre o que é essa versão que é para pegarmos?
